### ISSUE TITLE
Current plan to split this repository

### ISSUE THREAD

**Issue by HealthyPear** [HealthyPear/protopipe-grid-interface#5]
Not all the code contained in this repository requires the same environment.

In particular, as explained in the `README`, **2 environments** are needed:

- the `DIRAC/CTADIRAC` environment,
- the `protopipe` environment.

Some of the files **require DIRAC** (current candidates for migration under `CTADIRAC/Interfaces/API`):

- `example_configuration.cfg`, to configure the job sent on the grid
- `submit_jobs_new_scheme.py`, to send the job on the grid
- `delete_files.py`, to delete files on the grid
- `download_files.py`, to download filed from the grid
- `upload_file.py`, to upload files (aka the model estimators trained locally) to the grid

of which the first 2 are `protopipe`-specific, while the other 3 are for general purpose (but set to work within the `protopipe` workflow).

Some files are **Bash scripts**:

- `pilot.sh`, required to launch the job,
- `example_upload_models.sh`, required to configure `upload_file.py` based on the protopipe workflow,
- `example_download_and_merge.sh`, same but for downloading and merging in one step.

The rest of the code needs only protopipe or general python,

- `merge_tables.py`, to merge the files downloaded from the grid (currently done together with the download operations through a correctly edited `example_download_and_merge.sh`,
- `example_split_jobs.py`, to split lists of simulation files for each particle type.

**Note:** the merging code could be moved to protopipe and the merging itself could be done by temporarily switching envs from grid to protopipe and viceversa.

Last, the **`README` file**, which contents are planned to be moved to the protopipe's docs (#2).

**Comment by bregeon** [comment]
As I expected, these scripts are the heritage of Tino, and **we do not want to start from these**:

- There is not much added value in the delete/download/upload files script, and if we really need such dedicated scripts it's better to use the Dirac API rather than wrapping the Dirac scripts.
- example_configuration.cfg and submit_jobs_new_scheme.py fully mix configurations linked to the GRID aspects, and configurations of the various protopipe applications, what make these 2 files not human readable.

We really need to sit down and talk the protopipe workflow from scratch to understand how to interface this correctly to CTADIRAC.

As an example, the DL1 Data Handler job interface can be found here:
-  https://github.com/cta-observatory/CTADIRAC/blob/master/Interfaces/API/Prod3DL1DataHandlerJob.py
- https://github.com/cta-observatory/CTADIRAC/blob/master/Interfaces/test/prod3_dl1_data_handler_launcher.py

This interface is not perfect, but a priori, the protopipe interface should look quite similar.
Note also, that I expect that we'll have one interface per tool, e.g. one for DL0 to DL1, one for DL1 to DL2, one for DL2 to DL3, then may be also one for merging. These interfaces will likely inherit from a common protopipe interface.
